# This is a basic workflow to help you get started with Actions

name: Deploy Github Page

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permission: 
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Node.js environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        
      - run: npm install
      - run: npm run docs:build
      
      # To Github Page
      - name: To Github Page
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          publish_dir: ./docs/.vitepress/dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
