
name: Deploy Github Page

# 每当 push 到 master 分支时触发部署
on:
  # 在【master】分支推送事件时触发工作流
  push:
    branches: [master]

# 设置执行权限
permissions:
  contents: write

# 定义工作流
jobs:

  checkout:
    runs-on: ubuntu-latest
    
    # 定义步骤
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


  npm install:
    runs-on: ubuntu-latest

    # 定义步骤
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4

      - run: npm install
      - run: npm run docs:build


  deploy:
    runs-on: ubuntu-latest

    # 定义步骤
    steps:
      # 步骤：部署至gh-pages分支
      - name: To Github Page
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          publish_dir: ./docs/.vitepress/dist
          github_token: ${{ secrets.GITHUB_TOKEN }}
